version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    image: ws_3_db_image
    container_name: usersdb3
  standalone:
    build:
      context: ./standalone
    image: ws_3_standalone_image
    container_name: standalone3
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 8000:8000
